services:
  # Laravel PHP-FPM container
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: silog-app
    volumes:
      - .:/var/www
    networks:
      - backend
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=silog
      - DB_USERNAME=silog
      - DB_PASSWORD=7rlK0wLCM0exeut

  # Nginx container
  nginx:
    image: nginx:1.27
    container_name: silog-server
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www
      - ./storage:/var/www/storage
    ports:
      - "5001:80"
    networks:
      - backend
    depends_on:
      - app

  # MySQL container
  db:
    image: mysql:8.1
    container_name: silog-db
    environment:
      MYSQL_ROOT_PASSWORD: 7rlK0wLCM0exeut
      MYSQL_DATABASE: silog
      MYSQL_USER: silog
      MYSQL_PASSWORD: 7rlK0wLCM0exeut
    ports:
      - "3306:3306"
    networks:
      - backend

  # Cloudbeaver container (for DB management)
#   cloudbeaver:
#     image: dbeaver/cloudbeaver:latest
#     container_name: silog-cloudbeaver
#     ports:
#       - "8978:8978"
#     environment:
#       - CB_USER=admin
#       - CB_PASSWORD=7rlK0wLCM0exeut
#     networks:
#       - backend

networks:
  backend:
    driver: bridge
